### ISSUE TITLE
Do we need `when_race()`?

### ISSUE THREAD

**Issue by lionel-** [gaborcsardi/async#76]
I missed an issue in the `cleanup_tree` tests because errors thrown in `action` are silently ignored in `when_any()`. Is this expected behaviour? I would have expected an error here.

```r
defer_fail <- function() {
  deferred$new(action = function(resolve) stop("foo"))
}

synchronise(when_all(
  delay(0.1),
  defer_fail()
))
#> Error:
#> ! foo

synchronise(when_any(
  delay(0.1),
  defer_fail()
))
#> [1] TRUE
```

**Comment by gaborcsardi** [comment]
Yeah, that's what `when_any()` does. It is OK as long as one promise is OK.

**Comment by lionel-** [comment]
I think this is going to swallow unexpected errors too often.

Shouldn't it be explicit that an error should be ignored, e.g. with a tool like:

```r
async_catch <- async(function(expr) {
  tryCatch(
    await(expr),
    error = function(err) {
      if (inherits(err, "async_rejected")) {
        err$data$result %||% err
      } else {
        err
      }
    })
})
```

But even if `when_any()` is the way to do that implicitly, it still feels like there should be a `when_any()` variant that doesn't ignore errors?

**Comment by lionel-** [comment]
Another case where this would unexpectedly swallow errors: Using `when_any()` to trigger a tick:

```r
async_tick <- async(function() {
  repeat {
    writeLines("tick")
    await(async::delay(1))
  }
})

synchronise(when_any(
  async_tick(),
  defer_fail()
))
```

This ticks forever because the failing task was ignored.

**Comment by gaborcsardi** [comment]
The idea is that any promise is good, we don't care what happened to the others. E.g. when downloading a file from several possible URLs.

When would you be interested in the error a promise if another one successfully finished?

**Comment by lionel-** [comment]
I can see how it makes sense to ignore certain sort of errors like download errors, but if there is a programming / state / consistency error, I would like my program to fail and let me know that something is wrong.

**Comment by lionel-** [comment]
It looks like `when_any()` is like `Promise.any()` [1] and I was expecting it to be `Promise.race()` [2].

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any
[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race
