### ISSUE TITLE
Cannot find `synchronise` function

### ISSUE THREAD

**Issue by dereckmezquita** [gaborcsardi/async#79]
I'm looking for a package to allow me to have a non-blocking async event loop in R. I was trying one of your hello worlds and I get the error:

```r
library("async")

http_status <- function(url, ...) {
  http_get(url, ...)$
    then(function(x) x$status_code)
}

synchronise(http_status("https://eu.httpbin.org/status/418"))
```

```
r$> synchronise(http_status("https://eu.httpbin.org/status/418"))
Error in synchronise(http_status("https://eu.httpbin.org/status/418")) : 
  could not find function "synchronise"
```

I have installed `async` correctly so not sure what the issue is. I saw on the source code for `synchronise` `#' @export` is marked. Also, where does the http_get function come from?

**Comment by gaborcsardi** [comment]
Is it possible that you installed the async package from CRAN, which is a completely different package?

**Comment by dereckmezquita** [comment]
You're right I did; did not expect that thank you. Thank you for the package I'm very interested. I've been looking for something like this and would be interested in helping to build it - I need this.

I've tried a number of packages and they all have small things that keep me from using them. I'm looking for something that reproduces the async non-blocking event loop of `nodeJS` or something close to it so I can do `async` programming on my server in R.

I'm happy to see it seems to work with `Rscript`; this is something I've been looking for! Although I'm having it print twice on my hello world. I'll have to read the docs more and learn.

```r
#!/usr/bin/env Rscript
box::use(async)

main <- function() {
    async$delay(1)$then(\() {
        print("Hello")
    })$then(\() {
        print("World")
    })
}

async$synchronise(main())
```

Three questions if I may:

1. Are there any other docs or just the `README.md`?
1. How stable is the interface? I noticed you're on `0.0.0.9004` are there any big changes planned?
1. How does it work? I ask because I want to anticipate memory usage (possibly clones objects into subprocesses/forks for callbacks/promises) - and want to know if it would support using db connections in async code?

**Comment by gaborcsardi** [comment]
The second `"World"` is the return value:
```
❯ ret <- async$synchronise(main())
[1] "Hello"
[1] "World"

❯ ret
[1] "World"
```

1. You can try reading the the manual.
2. Pretty stable, I think. FWIW r-lib/pak uses this code internally.
3. Please read the manual, if you have specific questions, I'll be happy to answer them. DB connections are tricky, because R's DB packages are not async.
