### ISSUE TITLE
Github Discussions and how to cancel timers after X amount of time/understanding the event loop

### ISSUE THREAD

**Issue by dereckmezquita** [gaborcsardi/async#80]
@gaborcsardi could you please turn on the Discussions section on the repo. I would hate to create an issue and annoy you all everytime I have a question or something to discuss.

I have come back to my project that uses `async`, so once again thank you for the package.

I am working on implementing an event loop. I really want to get something that works as close to `NodeJS`'s event loop to allow me to write non blocking async code. I have done research into the `later` package as well but find that it doesn't suit my needs 100%.

Currently I am working on this minimal example but I can't get it to cancel timers after X amount of time. I am not sure what I've done wrong here. 

```R
library("async")

main <- function() {
    cat("Hello from beginning of script\n")

    interval1_counter <- 0
    interval2_counter <- 0

    interval1 <- async_timer$new(1.5, function() {
        cat("Hello from timer 1!", interval1_counter, "\n")
        interval1_counter <<- interval1_counter + 1
    })

    interval2 <- async_timer$new(1, function() {
        cat("Hello from timer 2!", interval2_counter, "\n")
        interval2_counter <<- interval2_counter + 1
    })

    delay(1)$then(function() {
        cat("Cancelling interval 1!\n")
        interval1$cancel()
    })

    delay(15)$then(function() {
        cat("Cancelling interval 2!\n")
        interval2$cancel()
    })

    cat("Hello from end of script\n")
}

run_event_loop({
    main()
})
```

I would expect interval 1 to be cancelled after only 1 second but it keeps running.

What I really want is something that behaves like this:

```js
console.log("Hello from begining of script");

let interval1_counter = 0;
const internval1 = setInterval(() => {
    console.log("Hello from timer 1! " + interval1_counter);
    interval1_counter++;
}, 1500);

let interval2_counter = 0;
const internval2 = setInterval(() => {
    console.log("Hello from timer 2! " + interval2_counter);
    interval2_counter++;
}, 1000);

setTimeout(() => {
    console.log("Cancelling interval 1!")
    clearInterval(internval1);
}, 10_000);

setTimeout(() => {
    console.log("Cancelling interval 2!")
    clearInterval(internval2);
}, 15_000);

console.log(internval1);

console.log("Hello from end of script");
```

The reason is because I am building a trading bot based on R. My programme is written in R6 classes, where I have a manager class that holds a list of trade bot instances. Each trade bot has a run method where they run on an interval. I would also be running a RestRserve REST API for interacting with the bot in the same session.

From my understanding what I could do is to wrap my whole programme in an event loop `async::run_event_loop` this way my bots would not block each other; whereby the bots run methods are built on `async::async_timer`s.

I have also done tests and found that I can run RestRserve on a background (forked) process. 

Does that sound right? I am looking for guidance and discussion. 

Finally I would like to support development of your package if you turn on GitHub sponsorship.

**Comment by gaborcsardi** [comment]
`delay()` creates a deferred value, which is only evaluated on demand. Deferred values are not like node.js promises. Deferred values are lazy, node.js promises are eager.

If you use another timer, that works, timers are eager:

```r
library("async")

main <- function() {
    cat("Hello from beginning of script\n")

    interval1_counter <- 0
    interval2_counter <- 0

    interval1 <- async_timer$new(1.5, function() {
        cat("Hello from timer 1!", interval1_counter, "\n")
        interval1_counter <<- interval1_counter + 1
    })

    interval2 <- async_timer$new(1, function() {
        cat("Hello from timer 2!", interval2_counter, "\n")
        interval2_counter <<- interval2_counter + 1
    })

    delay(1)$then(function() {
        cat("Cancelling interval 1!\n")
        interval1$cancel()
    })

    delay(15)$then(function() {
        cat("Cancelling interval 2!\n")
        interval2$cancel()
    })

    c1 <- async_timer$new(1, function() {
		interval1$cancel()
        c1$cancel()
    })

    c2 <- async_timer$new(15, function() {
		interval2$cancel()
        c2$cancel()
    })

    cat("Hello from end of script\n")
}

run_event_loop({
    main()
})
```

Or even better, use `synchronise()` to create an event loop. `main()` should return the deferred value that you want to evaluate.

```
library("async")

main <- function() {
    cat("Hello from beginning of script\n")

    interval1_counter <- 0
    interval2_counter <- 0

    interval1 <- async_timer$new(1.5, function() {
        cat("Hello from timer 1!", interval1_counter, "\n")
        interval1_counter <<- interval1_counter + 1
    })

    interval2 <- async_timer$new(1, function() {
        cat("Hello from timer 2!", interval2_counter, "\n")
        interval2_counter <<- interval2_counter + 1
    })

    d1 <- delay(1)$then(function() {
        cat("Cancelling interval 1!\n")
        interval1$cancel()
    })

    d2 <- delay(15)$then(function() {
        cat("Cancelling interval 2!\n")
        interval2$cancel()
    })

    cat("Hello from end of script\n")

   when_all(d1, d2)
}

synchronise(main())
```

**Comment by dereckmezquita** [comment]
Wonderful, I had not understood the distinction between eager and deferred objects. This is exactly what I was after thank you :) !

Would you like me to copy the question over to the Discussions section?

**Comment by gaborcsardi** [comment]
No need, it is fine here.
